<?php

namespace app\common\controller;
use Firebase\JWT\JWT;

class Base extends Corss
{
  protected function initialize()
  {
    parent::initialize(); // TODO: Change the autogenerated stub
    //判断有无token
    $header = request()->header();
    if (!isset($header['token'])) {
      $this->error('请先进行登录');
    }
    if (empty($header['token'])) {
      $this->error('请先进行登录');
    }
    //解析token
    $jwt = new JWT();
    try {
      $info = $jwt::decode($header['token'],config('jwt.key'),['HS256']);
    } catch (\Exception $e) {
      //请求失败
      if ($e->getMessage()=='Expired token') {
        $this->result(null,404,'登录态失效，请重新登录');
      }
    }

    //把用户信息往下传
    $this->aid = $info->aid;
  }
}
